$changes_ps = git diff head --name-only | where-object {$_ -like "*.ps1" -or $_ -like "*.psm1"}
$changes_tf = git diff head --name-only | where-object {$_ -like "*.tf" -or $_ -like "*.tfvars"}

#PowerShell
if ($changes_ps) {

	write-output "This is a pre-commit PowerShell call"
	write-output "======================================="

	$output = @()

	foreach ($change in $changes_ps) {
		$winPath = $change.replace("/", "\")
		$winPath = ".\$winPath"
		#write-output $winPath
		if (Test-Path -Path $winPath) {
			$out = Invoke-ScriptAnalyzer -Path $winPath -severity Error, ParseError
			$output += $out
		}
	}

	if ($output.Count -ne 0) {
		Write-Output "Basic scripting errors were found in updated scripts. fix or use git commit --no-verify"
		write-output "======================================="
		$output
		exit 1
	}
	else {
		Write-Output "pre-commit PowerShell call succeeded"
		Write-Output "                                    "
	}
}


#Terraform tflint
if ($changes_tf) {
	
	write-output "This is a pre-commit terraform tflint call"
	write-output "======================================="

	$output = @()
	
	$out = tflint --format json
	$output += $out

	#write-output $output
	#write-output $output.Count

	$valid = "{`"issues`":[],`"errors`":[]}"
	#write-output $valid

	if ($output -eq $valid) {
		Write-Output "pre-commit terraform tflint call succeeded"
		Write-Output "                                          "
		#tflint
	}
	else {
		Write-Output "syntax errors were found in updated scripts. fix or use git commit --no-verify"
		write-output "======================================="
		tflint
		exit 1
	}
}


#Terraform validate
if ($changes_tf) {
	
	write-output "This is a pre-commit terraform validate call"
	write-output "======================================="

	terraform init -backend=false
	$out = terraform validate -json | convertfrom-json

	#write-output $out.error_count

	if ($out.error_count -eq 0) {
		Write-Output "pre-commit terraform validate call succeeded"
		terraform validate
		#Remove the files generated by terraform init 
		Remove-Item -LiteralPath ".terraform" -Force -Recurse
		Remove-Item -Path ".terraform.lock.hcl" -Force
	}
	else {
		Write-Output "syntax errors were found in updated scripts. fix or use git commit --no-verify"
		write-output "======================================="
		terraform validate
		#Remove the files generated by terraform init 
		Remove-Item -LiteralPath ".terraform" -Force -Recurse
		Remove-Item -Path ".terraform.lock.hcl" -Force
		exit 1
	}
}