apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aks-claim
spec:
  storageClassName: aks-storageclass        #binding parameter with PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi