kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aks-storageclass
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain                               #volume won't get deleted when pod dies

# kubectl- deploy -f aks_storageclass.yml -n=azdo