# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:
- name: Package
  displayName: Package
  type: string
  #default: none
  # values:
  # - Nugett1
  # - Nugett2
  # - Nugett3
  # - Nugett4

pool:
  name: default

stages:
-  stage: stage1
   displayName: stage1
   jobs:
   - job: Nuget
     pool:
       name: Default
     steps: 
     
     - task: NuGetToolInstaller@1
       displayName: 'Use NuGet '

     - task: powershell@2
       displayName: 'Create psd1 file'
       inputs:
         targetType: 'inline'
         script: |
           New-ModuleManifest -Path .\${{ parameters.Package }}.psd1
         workingDirectory: '$(Build.SourcesDirectory)/${{ parameters.Package }}'

     - task: powershell@2
       displayName: 'Create nuspec file'
       inputs:
         targetType: 'inline'
         script: |
           nuget spec ${{ parameters.Package }} 
         workingDirectory: '$(Build.SourcesDirectory)/${{ parameters.Package }}'
  
     - task: powershell@2
       displayName: 'Create nupkg file'
       inputs:
         targetType: 'inline'
         script: |
           nuget pack ${{ parameters.Package }}.nuspec 
         workingDirectory: '$(Build.SourcesDirectory)/${{ parameters.Package }}'

     - task: NuGetCommand@2
       displayName: 'NuGet push'
       inputs:
         command: 'push'
         packagesToPush: '${{ parameters.Package }}/**/*.nupkg'
         nuGetFeedType: 'internal'
         publishVstsFeed: '8b1ca41e-0e01-4148-a4f5-b8fb46f34754/b19e422c-03ff-479b-b489-d3c3eabfbcc9'       # feed name converted to id
